version: '3'
services:
    make:
        build: '.'
        image: 'jehtech:latest'
        volumes:
            - '..:/jehtech'
        entrypoint: [ "bash", "/scripts/docker_script.sh" ]

    # Use docker-compose run --rm test
    test:
        image: 'jehtech:latest'
        volumes:
            - '..:/jehtech'
        stdin_open: true # docker run -i
        tty: true        # docker run -t
        entrypoint: [ "bash" ]

    upload:
        build: '.'
        image: 'jehtech:latest'
        volumes:
            - '..:/jehtech'
        entrypoint: [ "bash", "/scripts/docker_script.sh" , "DEPLOY" , ">", "/proc/1/fd/1"]
