version: '3'
services:
    make:
        build: '.'
        image: 'jehtech:latest'
        volumes:
            - '..:/jehtech'
        entrypoint: [ "bash", "/scripts/docker_script.sh" ]

    upload:
        build: '.'
        image: 'jehtech:latest'
        volumes:
            - '..:/jehtech'
        entrypoint: [ "bash", "/scripts/docker_script.sh" , "DEPLOY" , ">", "/proc/1/fd/1"]
