--- 
name: Build website and deploy to AWS

on: 
  push:
    branches:
      - master

jobs:
  build-and-deploy-to-aws:
    runs-on: ubuntu-latest
    environment: deploy
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2 # Depth is DELIBERATELY 2 so that commits straight to master can be see files changed. I dont bother with PRs - its only my crappy notes site!
      - uses: actions/setup-node@v3
        with:
          node-version: 16.13.2
          cache: 'npm'
      - run: npm ci
      - uses: actions/setup-python@v4
        with:
          python-version: '3.8.12'
          cache: 'pip'
      - run: pip3 install wheel
      - run: pip3 install -r requirements.txt
      - run: >
          cd build_tools 
          && chmod +x generate_html.sh 
          && make -j$(lscpu | grep "^\s*CPU(s):" | sed 's/.*:\s*//g') deploy
        env:
          AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}