--- 
name: Build website and deploy to AWS

on: 
  push:
    branches:
      - master

jobs:
  build-and-deploy-to-aws:
    runs-on: ubuntu-latest
    environment: deploy
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - uses: actions/setup-node@v3
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: eu-west-2
      - run: npm -v
      - run: >
          npm install -g @node-minify/core
          @node-minify/cli
          @node-minify/cssnano
          @node-minify/uglify-es
          @babel/core 
          @babel/cli
          @babel/preset-env
          esm
          mathjax@3
          yargs@3
          html-linter
          html-validate
      - run: npm -g list
      - run: sudo apt-get update
      - run: sudo apt-get install -y python3-pip
      - run: sudo pip3 install lxml pillow pyhash awscli boto3 markdown pymdown-extensions
      - run: cd build_tools && chmod +x generate_html.sh && make -j$(lscpu | grep "^\s*CPU(s):" | sed 's/.*:\s*//g') all && make deploy
        env:
          AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}