--- 
name: deploy-to-aws
on: [push]
jobs:
  deploy-to-aws:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - run: npm -v
      - run: npm install
      - run: @node-minify/core
      - run: @node-minify/cli
      - run: @node-minify/cssnano
      - run: @node-minify/uglify-es
      - run: @babel/core 
      - run: @babel/cli
      - run: @babel/preset-env
      - run: esm
      - run: mathjax@3
      - run: yargs@3
      - run: html-linter
      - run: html-validate
      - run: apt-get update
      - run: apt-get install -y python3-pip vim dos2unix
      - run: pip3 install lxml pillow pyhash awscli boto3 markdown pymdown-extensions
      - run: echo "$(pwd)"