name: deploy-to-aws
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: >
        npm install
          @node-minify/core
          @node-minify/cli
          @node-minify/cssnano
          @node-minify/uglify-es
          @babel/core @babel/cli
          @babel/preset-env
          esm
          mathjax@3
          yargs@3
          html-linter
          html-validate
      - run: apt-get update
      - run: apt-get install -y python3-pip vim dos2unix
      - run: pip3 install lxml pillow pyhash awscli boto3 markdown pymdown-extensions
      - run: echo "$(pwd)"