--- 
name: deploy-to-aws
on: [push]
jobs:
  deploy-to-aws:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - uses: actions/setup-node@v3
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: eu-west-2
      - run: npm -v
      - run: npm install -g @node-minify/core
      - run: npm install -g @node-minify/cli
      - run: npm install -g @node-minify/cssnano
      - run: npm install -g @node-minify/uglify-es
      - run: npm install -g @babel/core 
      - run: npm install -g @babel/cli
      - run: npm install -g @babel/preset-env
      - run: npm install -g esm
      - run: npm install esm
      - run: npm install -g mathjax@3
      - run: npm install -g yargs@3
      - run: npm install -g html-linter
      - run: npm install -g html-validate
      - run: npm -g list
      - run: sudo apt-get update
      - run: sudo apt-get install -y python3-pip
      - run: sudo pip3 install lxml pillow pyhash awscli boto3 markdown pymdown-extensions
      - run: cd build_tools && chmod +x generate_html.sh && make -j$(lscpu | grep "^\s*CPU(s):" | sed 's/.*:\s*//g') all && make deploy
        env:
          AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}